apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80           # Port trên service
    targetPort: 80      # Port trên container Nginx
    nodePort: 30007     # Port để truy cập từ bên ngoài (chọn số trong khoảng 30000-32767)
