apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-web
  template:
    metadata:
      labels:
        app: static-web
    spec:
      containers:
        - name: static-web-container
          image: localhost:5000/static-web:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: dockersecret
---
apiVersion: v1
kind: Service
metadata:
  name: static-web-service
spec:
  selector:
    app: static-web
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
